env:
  global:
     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
     # via the "travis encrypt" command using the project repo's public key
     #- secure: "OAtz9NT19jb1/mvQ1v3Hyfasy5RQFryBtKK4wQUKtb2eP4KkqzO6TduqrAf+EZDck3LMf2VfqJxlEG7sBFVDz0KWDRzmGFc4J5j/iWpo4rA/2oWjGxzpgH8Sj8M2duLmYb1q4b3GLb04XJ3evtNVk0ATQqDYA9aiezZdAPdl5EHgXV6dBCFuH2lU2UQCNE5zVnTmeKneVevDDLuihVr0FoGU0NpabdadY6WlKzFHhyJWYLvsYfsUFe6VoqeqdoiE+Pm074bkVr3b0v5Yln48HOLc14TwqHT/3nGEwwzfPEMSWKQvcUMBCoykp/PXBklIwZmA4c+eD0NeFXal2RibSfSaUePjJ3l49KLLhgDB67qK4clBPkdX4a01bELVEzlM8tc7a+Zn36vplHeMD9ECeK07MTCtSRC+0/rWSS7nlkWRjlH6veP3SRtnRehjgnx3wZ6xcoThnfkvKcUrOvKgVsdbcTAU6A4u487Quox/1EsZq5bcaqCaHKsr/8yOfPbLS378JbgtEREjR37GbEafD/th+jX8A90ZcNZ1VjDlAjEjb2SYO4tHH+aKEBv7iM8aM6i2afvyQ79paLCKT//eaqhqAYt3ZJCeKJPqGI1CNqBL9WUNgPaB7Pe9KriRgrVZi+zVSIpYXnPWKOsB1PuxpiYcplfE4tkXbxxMHle/jk4="

dist: trusty
sudo: required  # Needed to install Coverity certificate

language: c

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo apt-get install cmake libcunit-dev libexpat-dev
# - sudo dpkg -L libyaml-cpp-dev
# - sudo find / -name yaml-cpp
# - sudo find / -name yaml.h 
# - sudo find / -name 'libyaml-cpp.*' 
  - mkdir m4
  - autoreconf -i
  - ./configure --enable-debug

addons:
  coverity_scan:
    project:
      name: "semmerson/udunits-2"
      description: "Build submitted via Travis CI"
    notification_email: emmerson@ucar.edu
    build_command_prepend: true
    build_command:  "make"
    branch_pattern: coverity_scan

script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make all check >&make.log; fi

after_failure:
  - cat config.log
  - cat make.log
  - files=`find . -name test\*.log`; cat ${files:-/dev/null}
